OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyDdJ1l_FvgfVEFWR0M6AldYqnuywNQAbAY"
GOOGLE_CSE_ID = "634f56465c3744acf"